// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxhagkztllvbqpgtwtpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4aGFna3p0bGx2YnFwZ3R3dHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxOTMxMDYsImV4cCI6MjA1Mjc2OTEwNn0.uRjvLWEqq8z_vv7jbQqqCDSI6y6Ygr6VXOoZWjU1ca4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);