// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgjspuxwgamoztendeac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnanNwdXh3Z2Ftb3p0ZW5kZWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzE1MDQsImV4cCI6MjA1NzEwNzUwNH0._FW0WXvXUrypO7qcQUpblnBXryifDGe6OI9uCZQlIjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);